#!/usr/bin/env python
import sys
#pairs = sys.argv[1].split('_')
# for pair in pairs:
#     f = pair.split('-')
#     if f[0] == 'med':
#         mass = float(f[1])
#         width = 0.003 * mass

# this parameters are fixed and will not be changed for this model
print " -e s@XX-GS-XX@1.0@ -e s@XX-GDMS-XX@1.0@ -e s@XX-GP-XX@0.0@ -e s@XX-GDMP-XX@0.0@"
